export const API_RESPONSE = {
  CODE500: 500,
  CODE401: 401,
  CODE403: 403,
  CODE200: 200,
  CODE204: 204,
  CODE201: 201,
};

export const Login = {
  DESCRIPTION:
    'Keep track of your games and practices, register for new programs and teams, book rental space with ease and make payments online.',
  EMAIL: 'Email',
  EMAIL_ID: 'Email id',
  SIGNIN: 'Sign In',
  LOGIN: 'Login',
  PASSWORD: 'Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  FORGOT_PASSWORD: 'Forgot password?',
  KEEP_LOGGED_IN: 'Keep me Logged In!',
  REMEMBER_ME: 'Remember Me',
  DONT_HAVE_ACCT: "Don't have an account?",
  ENTER_EMAIL: 'Enter email',
  ENTER_PASSWORD: 'Enter password',
  SIGNIN_ACCT: 'Sign In Account',
  VALID_EMAIL: 'Please enter valid email',
  PLEASE_ENTER_EMAIL: 'Please enter email',
  PLEASE_ENTER_PASSWORD: 'Please enter password',
  OR: 'OR',
  LOGIN_WITH_FACE_ID: 'Login with Face ID',
  WANT_LOGIN: 'Want to login? ',
};

export const ForgotPassword = {
  FORGOT_PASSWORD: 'Forgot Password',
  DESCRIPTION:
    "Please enter your email address and submit. We'll send your email with a link to reset your password.",
  EMAIL: 'Email Address',
  ENTER_EMAIL: 'Enter your email address',
  CONFIRM_EMAIL: 'Confirm Email Address',
  ENTER_CONFIRM_EMAIL: 'Confirm your Email',
  RESET_PASSWORD: 'Reset Password',
  SUBMIT_EMAIL: 'Submit Email',
  ICON: 'check-circle',
  DIALOG_TITLE: 'Please check your email',
  DIALOG_CONTENT: 'Please use the OTP to reset your password',
  DIALOG_OK_TITLE: 'Done',
  DIALOG_MESSAGE: `${'An OTP has just been sent to '}`,
};

export const MyActivityStr = {
  ACTIVITY: 'Activity',
};
export const ChildAccountStr = {
  ENTER_FNAME: 'Enter first name',
  ENTER_LNAME: 'Enter last name',
  ENTER_EMAIL: 'Enter email address',
};

export const ResetPassword = {
  ENTER_OTP: 'Enter OTP',
  RESET_PASSWORD: 'Reset Password',
  DESCRIPTION:
    'Please enter the OTP sent to your email address and enter the new password.',
  OTP: 'OTP',
  NEW_PASSWORD: 'New Password',
  PASSWORD: 'Password',
  ENTER_PASSWORD: 'Enter new password',
  // ENTER_PASSWORD: 'Enter your new password',
  PLEASE_ENTER_PASSWORD: 'Please enter your new password',
  ENTER_CONFIRM_PASSWORD: 'Enter new password',
  CONFIRM_PASSWORD: 'Confirm new password',
  CONFIRM_YOUR_PASSWORD: 'Enter new password',
  PLEASE_RE_ENTER: 'Please re-enter your password',
  OTP_REQUIRED: 'OTP required',
  RESET_PASS_SUCCESS: 'Reset Password successful! Please login again',
};

export const ChangePassword = {
  ENTER_OTP: 'Enter OTP',
  CHANGE_PASSWORD: 'Change Password',
  RESET_PASSWORD: 'Reset Password',
  DESCRIPTION:
    'Please enter the OTP sent to your email address and enter the new password.',
  OTP: 'OTP',
  NEW_PASSWORD: 'New Password',
  CURRENT_PASSWORD: 'Current Password',
  PASSWORD: 'Password',
  ENTER_PASSWORD: 'Enter new password',
  ENTER_CURRENT_PASSWORD: 'Enter current password',
  PLEASE_ENTER_PASSWORD: 'Please enter your new password',
  ENTER_CONFIRM_PASSWORD: 'Enter new password',
  CONFIRM_PASSWORD: 'Confirm new password',
  CONFIRM_YOUR_PASSWORD: 'Enter new password',
  PLEASE_RE_ENTER: 'Please re-enter your password',
  OTP_REQUIRED: 'OTP required',
  RESET_PASS_SUCCESS: 'Reset Password successful! Please login again',
};

export const VerifyEmailStr = {
  TITLE: "Let's keep you safe!",
  SUB_TITLE:
    'Please enter the OTP sent to your email address to verify your information.',
  OTP: 'OTP',
  ENTER_OTP: 'Enter OTP',
  OTP_NOT_RECEIVED: "Didn't receive an OTP?",
  RESEND_OTP: 'Resend ',
  VERIFY_EMAIL: 'Verify Email',
  CONFIRM_PASSWORD: 'Confirm new password',
  CONFIRM_YOUR_PASSWORD: 'Enter new password',
  PLEASE_RE_ENTER: 'Please re-enter your password',
  OTP_REQUIRED: 'OTP required',
  RESET_PASS_SUCCESS: 'Reset Password successful! Please login again',
};

export const CustomerDetails = {
  CUSTOMER_DETAILS: 'Customer Details',
  DESCRIPTION:
    'We need these additional details to help you setup for games, rentals and more...',
  PROFILE_PHOTO: 'Profile Photo',
  UPLOAD_BTN: 'UPLOAD',
  MAX_FILE_SIZE: 'Max upload file size 5 MB',
  EMAIL: 'Email Address',
  ENTER_EMAIL: 'Enter your email',
  DOB: 'Date of Birth',
  CONFIRM_DOB: 'Confirm Date of Birth',
  PERSONAL_DOB: 'Your personal DOB',
  PROCEED_TO_INVITATIONS: 'Proceed to Invitations',
  GRADUATION_YEAR: 'Graduation Year',
  CLOTHING: 'Clothing Size',
  BIRTH_CERTIFICATE: 'Birth Certificate (Optional)',
  CHOOSE_FILE: 'Choose File',
  UPLOAD_A_PDF: 'Upload a pdf less than 5 MB',
  FNAME: 'First Name',
  LNAME: 'Last Name',
  ENTER_FNAME: 'Enter your first name',
  ENTER_LNAME: 'Enter your last name',
  PLEASE_ENTER_FNAME: 'Please enter first name',
  PLEASE_ENTER_LNAME: 'Please enter last name',
  SELECT_IMAGE_FROM: 'Select Image Form',
  PICKER_OPTION: ['Camera', 'Gallery', 'Cancel'],
  DATE_PLACEHOLDER: 'MM/DD/YYYY',
  PHONE_NUMBER: 'Phone Number',
  PHONE_PLACEHOLDER: '+1 (xxx) xxx-xxxx',
  SELECT: 'Select',
  GENDER: 'Gender',
  STATE: 'State/Province/Region',
  CITY: 'City',
  ZIPCODE: 'Zip Code',
  ADDRESS: 'Enter address',
  ENTER_YEAR: 'Enter year',
  STREET_ADDRESS: 'Street Address',
  PROVIDE_UNIQUE_EMAIL: 'Please provide unique email',
  ENTER_PASSWORD: 'Enter password',
  PASSWORD: 'Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  YOUR_CHILD_DOB: "Your Child's DOB",
  CREATE_CHILD_ACCOUNT: 'Create Child Account',
  BIRTH_GRADUATION_YEAR_DIFF_ERROR:
    'Graduation year can not occur before the person birth year!',
  BUILD_PROFILE: 'Build Your Profile',
  BUILD_PROFILE_CONTENT:
    "We need these details to help you setup for games, rentals and more. We promise its the only time you'll have to fill these details",
  OPTIONAL_FIELDS_INFO:
    'These fields are optional because not all club are required these details',
  PENDING_FAMILY_INVITATION: 'Pending Family Invitation(s)',
  PENDING_FAMILY_CONTENT: 'All your existing family invitations in one place.',
  PENDING_FAMILY: 'It looks like you have pending invitation(s) to review.',
  HI: 'Hi',
  WELCOME_TO: ', Welcome to Natty Hatty',
};

export const AddChildAccountStr = {
  CUSTOMER_DETAILS: 'Customer Details',
  DESCRIPTION:
    'We need these additional details to help you setup for games, rentals and more...',
  PROFILE_PHOTO: 'Profile Photo',
  UPLOAD_BTN: 'UPLOAD',
  MAX_FILE_SIZE: 'Max upload file size 5 MB',
  EMAIL: 'Email',
  ENTER_EMAIL: 'Enter email',
  DOB: 'Date of Birth',
  CONFIRM_DOB: 'Confirm Date of Birth',
  PERSONAL_DOB: 'Your personal DOB',
  PROCEED_TO_ADD_FAMILY: 'Proceed to Add Family Member(s)',
  FINISH_CREATE_CHILD_ACCOUNT: 'FINISH & CREATE CHILD ACCOUNT',
  UPDATE_CREATE_CHILD_ACCOUNT: 'UPDATE & CREATE CHILD ACCOUNT',
  GRADUATION_YEAR: 'Graduation Year',
  CLOTHING: 'Clothing Size',
  BIRTH_CERTIFICATE: 'Birth Certificate (Optional)',
  CHOOSE_FILE: 'Choose File',
  UPLOAD_A_PDF: 'Upload a pdf less than 5 MB',
  FNAME: 'First Name',
  LNAME: 'Last Name',
  ENTER_FNAME: 'Enter first name',
  ENTER_LNAME: 'Enter last name',
  PLEASE_ENTER_FNAME: 'Please enter first name',
  PLEASE_ENTER_LNAME: 'Please enter last name',
  SELECT_IMAGE_FROM: 'Select Image Form',
  PICKER_OPTION: ['Camera', 'Gallery', 'Cancel'],
  DATE_PLACEHOLDER: 'MM/DD/YYYY',
  PHONE_NUMBER: 'Phone Number',
  PHONE_PLACEHOLDER: '+1 (xxx) xxx-xxxx',
  SELECT: 'Select',
  GENDER: 'Gender',
  STATE: 'State/Province/Region',
  CITY: 'City',
  ZIPCODE: 'Zip Code',
  ADDRESS: 'Enter address',
  STREET_ADDRESS: 'Street Address',
  PROVIDE_UNIQUE_EMAIL: 'Please provide unique email',
  ENTER_PASSWORD: 'Enter password',
  PASSWORD: 'Password',
  ENTER_CONFIRM_PASSWORD: 'Enter Confirm Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  YOUR_CHILD_DOB: "Your Child's DOB",
  CREATE_CHILD_ACCOUNT: 'Create Child Account',
  BIRTH_GRADUATION_YEAR_DIFF_ERROR:
    'Graduation year can not occur before the person birth year!',
  BUILD_PROFILE: 'Build Your Profile',
  BUILD_PROFILE_CONTENT:
    "We need these details to help you setup for games, rentals and more. We promise its the only time you'll have to fill these details",
  OPTIONAL_FIELDS_INFO:
    'These fields are optional because not all club are required these details',
  PENDING_FAMILY_INVITATION: 'Pending Family Invitation(s)',
  PENDING_FAMILY_CONTENT: 'All your existing family invitations in one place.',
  PENDING_FAMILY: 'It looks like you have pending invitation(s) to review.',
  ADD_MORE_CHILD: 'Add More Child Account(s)',
};

export const Signup = {
  CREATE_ACCT: 'Create an Account',
  DESCRIPTION:
    'Keep track of your games and practices, register for new programs and teams, book rental space with ease and make payments online.',
  SIGN_UP: 'Sign Up',
  ALREADY_HAVE_ACCT: 'Already have an account?',
  SIGNUP_ACCT: 'Sign Up Account',
  CONTINUE: 'Continue',
  RECEIVE_UPDATES:
    'I don’t want to receive updates from Natty Hatty related to marketing, product and feature updates, and promotions.',
  TERMS_CONDITION_DESC:
    "By checking this box you are creating a Natty Hatty account, and you agree to Natty Hatty's",
  TERMS: 'Terms of Use',
  AND: 'and',
  PRIVACY: 'Privacy Policy.',
  LOGIN: 'Log In',
  FNAME: 'First Name',
  LNAME: 'Last Name',
  EMAIL_ADD: 'Email Address',
  PASSWORD: 'Password',
  ENTER_FNAME: 'Enter first name',
  ENTER_LNAME: 'Enter last name',
  ENTER_CONFIRM_YOUR_PASSWORD: 'Enter your confirm password',
  PLEASE_ENTER_FNAME: 'Please enter first name',
  PLEASE_ENTER_LNAME: 'Please enter last name',
  PLEASE_PLEASE_TERM: 'Please select Terms and Conditions!',
};

export const PendingInvitations = {
  PENDING_INVITATIONS: 'Pending Invitation(s)',
  DESCRIPTION:
    "Were you invited to join a family account? It's time to accept to reject your invitation(s).",
  DONT_HAVE_REQ: "You don't have any pending invitations",
  INVITATIONS: 'Invitations',
  PROCEED: 'Proceed to Add Child Account(s)',
  HAVE_INVITE_FROM: 'You have a pending invitation from ',
  EMAIL_TYPE: 'EMAIL & PERMISSION TYPE',
  SUCCESS_TITLE: 'Invitation in Process',
  SUCCESS_MESSAGE:
    'We are sending your Invites You do not need to take any action at this time',
  SUCCESS_DONE: 'Finish Setup',
  DELETE_SUCCESS_DONE: 'Done',
  DELETE_SUCCESS_MESSAGE: 'Your invite(s) have been successfully deleted',
  INVITE_SUCCESSFULLY: 'Invitation Successfully',
  NO_INVITATIONS: 'You do not have any received invitations',
  NO_FAMILY_INVITATIONS: 'You do not have any family member’s invitation',
};

export const YourInvitations = {
  SEND_INVITE_FINISH_SETUP: 'Send Invite(s) & Finish Setup',
  FINISH_SETUP: 'Finish Setup',
  MEMBER: 'Member',
  ADMIN: 'Admin',
  PERMISSION: 'Permission',
  CHILD: 'CHILD',
};

export const MainMenuStr = {
  FAMILY_CONTROL_CENTER: 'Family Control Center',
  CONTROL_CENTER_SUB_TITLE:
    'My Account, manage family members, wallet, activities and invitations',
  SUPPORT_PLATFORM: 'Support Platform',
  RESOURCES: 'Resources',
  SETTING: 'Setting',
};

export const MyFamily = {
  ADD_MEMBER: 'Add Family Member(s)',
  DESCRIPTION:
    'Please add members to your household by entering their details or sending email invitation.',
  ADD_NEW_MEMBER: 'Add New Member',
  YOUR_CURRENT_FAMILY: 'Your Current Family',
  EMAIL: 'Email Address',
  ADD_FAMILY_MEMBER: 'Send Invite to Add Family Member(s)',
  INVITE_FAMILY: 'Invite Family',
  INVITE_FAMILY_MEMBER: 'Invite members to join your family',
  // ADD_FAMILY_MEMBER: 'Invite Member to Family',
  PERMISSION: 'Permission',
  ENTER_EMAIL: 'Enter email',
  ENTER_MEMBER_EMAIL: 'Enter email',
  OK: 'Ok',
  CONFIRM: 'Confirm',
  YES: 'Yes',
  Cancel: 'Cancel',
  ONLY_ADMIN_MESSAGE:
    'You can’t remove this member from the family as he/she is the only admin.',
  ONLY_GUARDIAN_MESSAGE:
    'You can’t remove this member from the family as he/she is the only guardian.',
  LEAVE_FAMILY: 'Leave Family',
  REMOVE: 'Remove',
  LEAVE: 'Leave',
  REMOVE_FROM_FAMILY: 'Remove From Family',
  LEAVE_ALERT: 'Are you sure you want to leave from this family?',
  HOLDON_MESSAGE:
    'Hold Tight! One or more admin requests are still pending. Please try again in sometime.',
  CREATE_ANOTHER_ADMIN:
    'Create another Admin in your family to change your Account Type',
  ALREADY_TWO_GUARDIAN: 'You Already have two Guardians!',
  NEED_ONE_GUARDIAN: 'You need to have at least one guardian in the family',
  GRADUATION_YEAR: 'Graduation year can not be less than birth of year',
  MEMBER_NOT_FOUND: 'Members not found',
  MY_FAMILY: 'My Family',
  ADD_NEW: 'Add New',
  SEARCH_FAMILY_MEM: 'Search family member',
  SEND_INVITE: 'Send Invite',
  CHILD_ACNT: 'Child Account',
  CHILD_ADD: 'Add Children',
};

export const MyAccountStr = {
  MY_ACCOUNT: 'My Account',
  PROFILE: 'Profile',
  WALLET: 'Wallet',
  ACTIVITY: 'Activity',
  INVITATIONS: 'Invites',
  FNAME: 'First Name',
  LNAME: 'Last Name',
  GRADUATION_YEAR: 'Graduation Year',
  PHONE_NUMBER: 'Phone Number',
  VIEW_MORE: 'View More',
  GUARDIAN: 'Guardian',
  ACCOUNT_TYPE: 'Account type',
  SAVE_CHANGES: 'Save',
  REMOVE_FROM: 'Remove',
  LEAVE_FAMILY: 'Leave Family',
  EDIT_PROFILE: 'Edit Profile',
  DELETE_SUCCESS_DONE: 'Done',
  DELETE_CERTIFICATE_MESSAGE: 'Your certificate have been successfully deleted',
  UPLOAD_CERTIFICATE_MESSAGE:
    'Your certificate have been successfully uploaded',
  PAYMENTS: 'Payments',
  BILLING_ADDRESS: 'Billing Address',
  NH_CREDITS: 'Natty Hatty Credits',
  TAB_PROFILE: 'PROFILE',
  TAB_FAMILY: 'FAMILY',
  TAB_DETAILS: 'DETAILS',
  TAB_WALLET: 'WALLET',
  TAB_ACTIVITY: 'ACTIVITY',
  TAB_INVITATION: 'INVITES',
  TAB_HOME: 'HOME',
  TAB_BILLING: 'BILLING',
  PLEASE_ADD_PAYMENTS_METHODS: 'Please Add Payments Methods',
};

export const Icons = {
  EYE: 'eye',
  CLOSE_EYE: 'eye-slash',
  CALENDER: 'calendar',
  UPLOAD: 'upload',
  DOWN_ARROW: 'down',
  PDF: 'pdffile1',
  DELETE: 'delete',
  CHECK_ICON: 'check',
  CLOSE_ICON: 'close',
  CHECK: 'checkcircle',
  CORSS_SQUARE: 'closecircle',
  AT_SIGN: 'at-sign',
  EDIT: 'edit',
};

export const AddNewMemberStr = {
  SENT_SUCCESS: 'Sent invitations successfully',
  EMAIL_ALREADY: 'Email already registered in another family',
  ADDED_EMAIL: 'Added Emails',
  SEND_INVITES: 'Send Invite(s)',
};

export const YourFamilyStr = {
  REMOVE_CONFIMATION: 'Are you sure you want to remove',
  THIS_MEM: 'this member',
  FROM_THE_FAMILY: 'from the family',
  YOUR_FAMILY: 'Your Family',
  ALL_THE_FAMILY: 'All the family members that have accepted invitation',
};

export const IconType = {
  ANTDESIGN: 'AntDesign',
  FEATHER: 'Feather',
  ENTYPO: 'Entypo',
  FONT_AWESOME: 'FontAwesome',
  MATERIAL: 'Material',
};

export const DateFormates = {
  MMDDYYY: 'MM/DD/YYYY',
  YYYYMMDD: 'YYYY/MM/DD',
  YYYY_MM_DD: 'YYYY-MM-DD',
  YYYYMMDDTHH: 'YYYY-MM-DDThh:mm:ss.000Z',
  MMMM_DD_YYYY: 'MMMM DD, YYYY',
  MMM_DD_YYYY: 'MMM DD, YYYY',
  MMMM_YYYY: 'MMMM YYYY',
  MMDDYY: 'MM/DD/YY',
  hhmmA: 'hh:mm A',
};

export const ProgramStr = {
  NEW_PROGRAMS: 'New Program',
  MY_PROGRAMS: 'My Program',
  CLUB_PROGRAMS: 'Club Programs',
  FACILITY_PROGRAMS: 'Facility Programs',
  SELECT_CLUB: 'Select Club',
  SELECT_PROGRAM: 'Select Program',
  SEARCH_PROGRAM: 'Search Program',
  SEARCH_TEAM: 'Search Team',
  CHOOSE_PROGRAM: 'Choose Program',
  PRICE_RANGE: 'Price Range',
  PROGRAM_EMAIL: 'Email:',
  PROGRAM_PHONE: 'Phone:',
  OPEN_PROGRAM: 'Open Programs:',
  VIEW_PROGRAM: 'View Programs',
  VIEW_DIVISION: 'View Division',
  REGISTER: 'Register',
  VIEW_ALL: 'VIEW ALL',
  REG_FEE: 'Reg. Fee',
  PROGRAM_BRAND: 'Brand (DBA):',
  PROGRAM_FACILITY: 'Facility:',
  PROGRAM_DIVISION: 'Divisions:',
  PROGRAM_START_DATE: 'Program Start Date:',
  PROGRAM_START_DATE_TIME: 'Program Start Date & Time:',
  PROGRAM_END_DATE: 'Program End Date:',
  PROGRAM_END_DATE_TIME: 'Program End Date & Time:',
  PROGRAM_REGISTRATION_DUE: 'Registration Due:',
  REGISTERED_ON: 'Registered On:',
  DOB_RANGE: 'DOB Range:',
  LEVEL: 'Level:',
  OPEN_SPOTS: 'Open Spots:',
  DIVISION_LISTS: 'Division(s) List',
  VIEW_NOTE: 'View Note',
  MESSAGE_CLUB: 'Message Club',
  MESSAGE_FACILITY: 'Message Facility',
  PROGRAM_NOTE: 'Program Note',
  NO_CLUB_FOUNDS: 'No club programs found!',
  NO_FACILITY_PROGRAM_FOUNDS: 'No facility programs found!',
  MEMBERS: 'Members:',
  CLUB_NAME: 'Club Name:',
  PAYMENT_STATUS: 'Payment Status:',
  OLDEST: 'Oldest',
  LATEST: 'Latest',
  PRICE_ASC: 'Price ASC',
  PRICE_DESC: 'Price Desc',
  REGISTER_ON_DESC: 'Registered on (New to Old)',
  PROGRAM_NAME_ASC: 'Program Name (A to Z)',
  PROGRAM_NAME_DESC: 'Program Name (Z to A)',
  NO_CLUB_PROGRAM_AVAILABLE: 'No club programs available!',
  NO_FACILITY_PROGRAM_AVAILABLE: 'No facility programs available!',
  BRAND_DBO: 'Brand (DBO):',
  FACILITY: 'Facility:',
  REGISTERED: 'Registered:',
  DIVISION_NAME: 'Division Name:',
  PROGRAM_START_END_DATE: 'Program Start & End Date:',
  VIEW_REQUEST: 'View Request',
  LEAGUE_STANDING: 'League Standing',
  GAMES: 'Games',
  INVITE_LIST: 'Invite(s) List',
  SEARCH: 'Search',
  SENT_ON: 'Sent On:',
  SENT_TO: 'Sent To:',
  LEAVE_PROGRAM: 'Leave Program',
  LEAVE_PROGRAM_MESSAGE: 'Are you sure you want to leave the program?',
  REQUEST_TO_LEAVE: 'Request to Leave',
  REQUEST_TO_LEAVE_MESSAGE: 'Please give a reason requesting to leave.',
  TYPE_HERE: 'Type here',
  VALID_REASON_TO_LEAVE: 'Reason for leave is required',
  CREATE_AT: 'Created at:',
  CREATE_ON: 'Created On:',
  REGISTRATION_DUE: 'Registration Due:',
};

export const FilterStr = {
  FILTERS: 'Filters',
  CLEAR_ALL: 'Clear All',
  PRICE_RANGE: 'Price Range',
  CATEGORY: 'Category',
  FAMILY_MEMBER: 'Family Member',
  SELECT_CATEGORY: 'Select Category',
  SELECT_FAMILY_MEMBER: 'Select Family Member',
  SELECT_GENDER: 'Select Gender',
  SELECT_LEVEL: 'Select Level',
  SELECT_TYPE: 'Select Request Type',
  SELECT_STATUS: 'Select Status',
  SELECT_TEAM: 'Select Team',
  PRODUCT_TYPE: 'Product Type',
  SELECT_PRODUCT_TYPE: 'Select Product Type',
  ENTER_MIN_MAX_DOB_DATE: 'Enter Min and Max Date of Birth',
  ENTER_MIN_MAX_PROGRAM_DATE: 'Program Start Date',
  MIN_DATE: 'Min Date',
  MAX_DATE: 'Max Date',
  DUE_DATE: 'Due Date',
  GENDER: 'Gender',
  LEVEL: 'Level',
  STATUS: 'Status',
  TEAMS: 'Teams',
  APPLY_FILTER: 'Apply Filter',
  INVITE_FOR: 'Invite For',
  SELECT_INVITE: 'Select Invite',
  SELECT_TEAM_ROLE: 'Select Team Role',
  PROGRAM_TYPE: 'Program Type',
  SELECT_PROGRAM_TYPE: 'Select Program Type',
};

export const FinanceStr = {
  FINANCIAL: 'Financial',
  INVOICES: 'Invoices',
  CLUB_INVOICES: 'Club',
  FACILITY_INVOICES: 'Facility',
  NH_CREDITS_INVOICES: 'NH Credit',
  DATE_ASC: 'Date (ASC)',
  DATE_DESC: 'Date (DESC)',
  SEARCH: 'Search',
  NO_INVOICES_FOUND: 'No Invoices Found',
  INVOICE_NUMBER: 'INVOICE NUMBER',
  BILLED_TO: 'BILLED TO',
  SENT_FROM: 'SENT FROM',
  SENT_ON: 'SENT ON',
  DATE: 'DATE',
  INVOICE_DATE: 'INVOICE DATE',
  AMOUNT: 'AMOUNT',
  AMOUNT_RECEIVED: 'AMOUNT RECEIVED',
  PAID: 'PAID',
  REIMBURSED: 'REIMBURSED',
  REIMBURSEMENT: 'REIMBURSEMENT',
  BALANCE: 'BALANCE',
  DISCOUNT: 'DISCOUNT',
  // DISCOUNT: 'DISCOUNT(%)',
  VIEW_INVOICE: 'View Invoice',
  INVOICE_DETAILS: 'Invoice Details',
  PRODUCTS: 'Product(s)',
  PRODUCT: 'PRODUCT',
  SHOW_MORE: 'SHOW MORE',
  SHOW_LESS: 'SHOW LESS',
  CATEGORY: 'CATEGORY',
  REIMBURSED_TYPE: 'REIMBURSED TYPE',
  PRODUCT_TYPE: 'PRODUCT TYPE',
  STATUS: 'Status',
  S_NO: 'S No.',
  DUE_DATE: 'DUE DATE',
  REGISTRATION_FEE: 'REGISTRATION FEE',
  PROGRAM_NAME: 'PROGRAM NAME',
  TEAM_NAME: 'TEAM NAME',
  TOTAL_AMOUNT: 'TOTAL AMOUNT',
  DETAILS: 'Details',
  Pay_Delinquent_Amount: 'Pay Delinquent Amount',
  NO_CARD_AVAILABLE: 'No card available. Please add a new card or bank account',
  PAY_NOW: 'Pay Now',
  PAID_VIA: 'PAID VIA',
  CC_BANK: 'CC/Bank',
  NATTY_HATTY_CREDIT: 'Natty Hatty Credit',
  RESOURCES_SIZE: 'RESOURCES SIZE',
  SUB_RESOURCE: 'SUB RESOURCE',
  DURATION: 'DURATION (HRS.)',
  RATE: 'RATE/HR.',
  PROGRAM: 'PROGRAM',
  DIVISION_NAME: 'DIVISION NAME',
  NATTY_HATTY_CREDIT_TRANSFER: 'NH CREDIT TRANSFER',
  FACILITY: 'FACILITY',
  RESOURCE: 'RESOURCE',
  START_DATE: 'START DATE',
  END_DATE: 'END DATE',
};

export const App = {
  BACK_BUTTON_TITLE: 'Back',
  BIOMETRIC_AUTH_TITLE: 'Biometric authentication',

  CANCEL: 'Cancel',
  NO_DATA_FOUND: 'No data found',
  COMING_SOON_TITLE: 'Coming soon',
  SELECT_PAYMENT_METHOD: 'Select Payment Method',
  COMING_SOON_MESSAGE:
    'Stay tuned. We are almost ready to launch. Something awesome is coming soon. Be first to know.',
};

export const memberSelectionStr = {
  TITLE: 'Select Member who you want to register',
  NO_MEMBER: 'No Family Member To Register !',
  PROCEED: 'Proceed to Next Step',
  SORT_BY: 'Sort by :',
  YOU_CANT: 'You can not select more than open spots.',
};

export const addChildFailureStr = {
  TITLE: 'Alert',
  SUB_TITLE:
    "The following children didn't add in your family due to some errors:",
  SKIP_BTN: 'Skip edit and proceed',
  EditBTN: 'Edit the children',
};

export const reviewWaiverStr = {
  TITLE: 'Review Waivers',
  PROCEED: 'Proceed to Next Step',
  CONDITION:
    'By checking this box, you are saying that you have read the waivers listed above and agree to their terms and conditions.',
};

export const programRequestStr = {
  PENDING: 'Pending',
  SETTLED: 'Settled',
  CONDITION:
    'By checking this box, you are saying that you have read the waivers listed above and agree to their terms and conditions.',
};

export const updateHomeAddStr = {
  UPDATE_SUCCESSFULLY: 'Home address updated successfully',
  ADDRESS: 'Address',
  UPDATE: 'Update',
};

export const checkoutStr = {
  SUMMARY: 'Summary',
  SELECTED_MEMBER: 'Selected Members',
  SELECTED_PAYMENT: 'Selected Payment Method',
  APPLICABLE_CREDIT: 'Applicable Credit',
  ATTENTION: 'ATTENTION:',
  READ_LESS: 'Read Less',
  READ_MORE: 'Read More',
  NAME: 'Name',
  APPLICABLE_TO: 'APPLICABLE TO:',
  CREDIT: 'CREDIT',
  TOTAL_MEM: 'Total Members Selected',
  TOTAL_PAYABLE: 'Total Payable Per Member',
  DUE_NOW: 'Due Now',
  TOTAL_PAYABLE_NOW: 'Total Payable Now',
  TNC: 'You have read the waivers listed below and agreed to their terms and conditions.',
  ATTENTION_TITLE:
    'You will receive a 1.96% discount on the amount paid with Natty Hatty Credit.',
  ATTENTION_TWO_TITLE:
    'You will not be charged until the program is confirmed.',
  NON_EX_FACILITY_PROG_REG_SUCCESS:
    'You have successfully registered for the facility program. Registered Member(s) are listed below and your account will be charged once the program is confirmed.',
  NON_EX_CLUB_PROG_REG_SUCCESS:
    'You have successfully registered for the club program. Registered Member(s) are listed below and your account has been charged.',
  TOTAL_AMOUNT_INFO_TEXT: 'Total Member(s) Selected x Registration Fee',
  SUCCESSFULLY_REG: 'Successfully Registered',
  VIEW_INVOICES: 'View Invioces',
  ATTENTION_TEAM_INVITE_CHECKOUT:
    'Payment will be charged automatically on due dates.',
  PAYMENT_PLAN: 'Payment Plan',
  DUE_DATE: 'Due Date',
  MEMBERS: 'Members',
  TEAM_FEES: 'Team Fees',
  TEAM_COACH_EXCLUSIVE_INVITE_REG_SUCCESS:
    'You have successfully registered for this team.',
  TEAM_NON_EXCLUSIVE_REG_SUCCESS:
    'You have successfully registered for this team. Registered Member are listed below and your account has been charged.',
};

export const requestProgramStr = {
  SEARCH: 'Search',
  SEARCH_REQ: 'Search requests',
  REGISTERED: 'Registered:',
  REQUEST_TYPE: 'Request Type:',
  REIM_TYPE: 'REIM. TYPE:',
  REIM_TYPE_FULL: 'Reimbursement Type:',
  AMOUNT: 'Amount:',
  NOTE_BY: 'Note by Facility:',
  DONE: 'Done',
  CANCELLED: 'Cancelled Request',
  REJECTED: 'Rejected Reschedule Request',
  REQUEST_REASON: 'Your Request Reason:',
  REQUEST_PENDING: 'Request Pending',
  AUTO_REMOVE: 'Auto Removed From Program',
  SETTLED_REQUEST: 'Settled Request',
  SETTLED_REMOVE_ICON: 'check-circle',
  PENDING_ICON: 'clock',
  CANCELLED_ICON: 'x',
  DELETE_MSG: 'Are you sure you want to cancel program request?',
  DELETE_TITLE: 'Cancel Program Request?',
  DELETE_TEAM_REQUEST_MSG: 'Are you sure you want to cancel team request?',
  DELETE_TEAM_REQUEST_TITLE: 'Cancel Team Request?',
  CANCEL_BTN: 'Cancel',
  OK_BTN: 'Submit',
};

export const DrawarStr = {
  SEARCH_REQ: 'Search requests',
  LOG_OUT: 'Log Out',
  YES: 'Yes',
  LOG_OUT_MESSAGE: 'Are you sure want to logout?',
};

export const AddBillingAddStr = {
  BILLING_DETAILS: 'Billing Details',
  ADD_LINE_ONE: 'Address Line 1:',
  ADD_LINE_TWO: 'Address Line 2:',
  COUNTRY: 'Country',
  SAVE_CHANGES: 'Save Changes',
};

export const AddBankAccountStr = {
  ARE_YOU_DELETE: 'Are you sure you want to delete this payment method?',
  DELETE_PAYMENT: 'Delete Payment Method',
  CONFIRM: 'Confirm',
  ADD_BANK_ACCOUNT: 'Add Bank Account',
  ACCOUNT_NUM: 'Account Number',
  ENTER_ACC_NUM: 'Enter Account Number',
  ACC_HOLDER_NAME: 'Account Holder Name',
  ENTER_ACC_HOLDER_NAME: 'Enter Account Holder Name',
  ROUTING_NUM: 'Routing Number',
  ENTER_ROUTE: 'Enter Route Number',
  UPDATE_ACC: 'Update Account',
  DELETE_ACC: 'Delete',
  CARD_HOLDER_NAME: 'Card Holder Name',
  HOLDER_NAME: 'Holder Name',
  CARD_DETAILS: 'Card Details',
  CARD_NUMBER: 'Card Number',
  ENTER_CARD_NUMBER: 'Enter Card Number',
  CVV: 'CVV (Security Code)',
  ENTER_CVV: 'ENTER CVV',
  EXPIRATION_DATE: 'Expiration date',
  DATE_PLACEHOLDER: 'MM/YY',
  ADD_BILLING_ADD: 'Billing Address',
  ADD_LINE_ONE: 'Address Line 1:',
  ADD_LINE_TWO: 'Address Line 2:',
  COUNTRY: 'Country',
  UPDATE_CARD: 'Update Card',
  ADD_CARD: 'Add Card',
  CREDIT_CARD_DETAILS: 'Credit Card Details',
};

export const NHCreditdsStr = {
  TOTAL_CREDITS: 'Total Credits',
  NH_CREDITS: 'Natty Hatty Credits',
  NO_NH_CREDITS: 'You don’t have natty Hatty credits yet ',
  SEARCH: 'Search',
};

export const PaymentsScreenStr = {
  PRIMARY: 'Primary',
  OTHERS: 'Others',
  ADD_PAYMENT_METHOD: 'Please Add Payment Method',
  ADD_NEW_PAYMENT_METHOD: 'Add New Payment Method',
  SEARCH: 'Search cards or account',
};

export const UpdateHomeAddressStr = {
  COUNTRY: 'Country',
  US: 'US',
};

export const FacilityProgramInviteScreenStr = {
  CANCEL: 'Cancel',
  REJECT_INVITATION: 'Reject Invitation',
  REJECT_CONFIRMATION:
    'Are your sure you want to reject the program invitation?',
};

export const SelectPaymentMethodeStr = {
  NO_CARD_MSG: 'No card available. Please add a new card or bank account',
  ADD_CREDIT_CARD: 'Credit Card',
  SELECT_PAYMENT_METHOD: 'Select Payment Method',
  PROCEED_NEXT_STEP: 'Proceed to Next Step',
  ADD_BANK_ACC: 'Bank Account',
  ADD_NEW: 'Add New',
};

export const CardListItemStr = {
  EDIT_CARD: 'Edit Card ',
  EDIT_ACCOUNT: 'Edit Account ',
  MAKE_PRIMARY: 'Make Primary ',
};

export const NHCardViewStr = {
  CVV: 'cvv',
  ROUTING_NUMBER: 'Routing Number',
  CARDHOLDER_NAME: 'Cardholder Name',
  VALID_THRU: 'Valid Thru',
};

export const SelectCardItemStr = {
  BILLING_ADDRESS: 'Billing Address',
};

export const ScreenNamesAndTitle = {
  MY_TEAMS: 'My Teams',
  CHAT: 'CHAT',
  MESSAGE: 'Message',
  CALENDAR: 'CALENDAR',
  BOOKING: 'BOOKINGS',
  BOOK_NOW: 'Book Now',
  BOOKING_INVITES: 'Booking Invites',
  TRAINERS: 'TRAINERS',
  BROWSE: 'Browse',
  BACK: 'Back',
  MY_ACCOUNT: 'My Account',
  NOTIFICATIONS: 'Notifications',
  HOME_ADDRESS: 'Home Address',
  APP_SCREENS: 'AppScreens',
  UPCOMING: 'Upcoming',
  PROGRAM_INVITES: 'Program Invites',
  PROGRAM_REQUEST: 'Program Request',
  PROGRAM: 'PROGRAMS',
  NEW_PROGRAM: 'New Programs',
  MY_PROGRAM: 'My Programs',
  TEAMS: 'TEAMS',
  NEW_TEAMS: 'New Teams',
  TEAM_REQUEST: 'Team Requests',
  EXCLUSIVE_INVITES: 'Team Invites',
  TEAM_BUILDER: 'Team Builder',
  EVENTS_REQUEST: 'Event Requests',
  INVOICES: 'INVOICES',
  VIEW_INVOICES: 'View Invoices',
  INVOICES_BILLING_INVITES: 'Billing Invitations',
  MY_SCHEDULE: 'My Schedule',
  TRAINER_INVITES: 'Trainer Invites',
  SHOP: 'SHOP',

  HOME: 'HOME',
  ACCOUNT: 'ACCOUNT',
  DRAWER: 'drawer',
  TEAM_INVITES: 'Team Invites',
  CREATE_CHILD_ACCOUNT: 'Create Child Account',
  NEW_CHAT: 'New Chat',
  CHAT_SMALLCASE: 'Chat',
  SETTING: 'SETTINGS',
  PROGRAM_TITLE: 'Leagues, tournament, tryouts & more',
  TEAM_TITLE: 'All your teams in one place',
  INVOICE_TITLE: 'All your transaction details',
  CALENDAR_TITLE: 'Shared family calendar',
  BOOKING_TITLE: 'Recreational spaces near me',
  TRAINERS_TITLE: 'Train more, Earn more',

  MY_PROGRAM_TITLE: 'Programs my family is registered in',
  NEW_PROGRAM_TITLE: 'Find & register for new programs',
  EXC_PROGRAM_TITLE: 'Special Invites for programs from facilities',
  REQUEST_PROGRAM_TITLE:
    'Check status of my program requests that i have sent to facilities',

  MY_TEAM_TITLE: 'Teams my family is registered in',
  NEW_TEAM_TITLE: 'Find & register for new teams',
  EXC_TEAM_TITLE: 'Special Invites for teams',
  REQUEST_TEAM_TITLE:
    'Check status of my team requests that i have sent to clubs',
  TEAM_BUILDER_TITLE: 'Build my own friendly teams',

  VIEW_INVOICE_TITLE:
    'View all the transaction details for clubs, facilities, Natty Hatty credits, bookings and bills',
  BILLING_INVOICE_INVITE_TITLE: 'Review my bills from facilities and clubs',

  BOOK_NOW_TITLE: 'Book fields, court and much more near me',
  BOOKING_INVITE_TITLE: 'Review invites from facilities to confirm my booking',

  MY_SCHEDULE_TITLE: 'View my upcoming lessons',
  TRAINER_INVITE_TITLE:
    'View, Accept & Reject trainer invites sent by facilities',
};

export const facilityProgramRequestSortingData = [
  {label: 'Submmited (New to Old)', value: 'req_date/DESC'},
  {label: 'Submmited (Old to New)', value: 'req_date/ASC'},
  {label: 'Settled (New to Old)', value: 'settled_on/DESC'},
  {label: 'Settled (Old to New)', value: 'settled_on/ASC'},
];

export const facilityProgramRequestTypeFilterData: any = [
  {label: 'Removal', value: 'removal'},
  {label: 'Auto Removal', value: 'auto_removal'},
  {label: 'Leave', value: 'leave'},
];

export const teamequestTypeFilterData: any = [
  {label: 'Auto Removal', value: 'auto_removal'},
  {label: 'Leave', value: 'leave'},
];

export const calendarEventRequestTypeFilterData: any = [
  {label: 'Reschedule', value: 'reschedule'},
  {label: 'Delete', value: 'delete_request'},
];

export const calendarEventRequestStatusFilterData: any = [
  {label: 'Removed', value: 'removed'},
  {label: 'Cancelled', value: 'cancelled'},
  {label: 'Pending', value: 'in_review'},
  {label: 'Settled', value: 'settled'},
  {label: 'Forfeit', value: 'forfeit'},
];

export const facilityProgramRequestStatusFilterData: any = [
  {label: 'Removed', value: 'removed'},
  {label: 'Cancelled', value: 'cancelled'},
  {label: 'Pending', value: 'in_review'},
  {label: 'Settled', value: 'settled'},
];

export const rosterProgramFilterData: any = [
  {label: 'Registration', value: 'Registration'},
  {label: 'Scheduling', value: 'Scheduling'},
  {label: 'Scheduled', value: 'Scheduled'},
  {label: 'Active', value: 'Active'},
  {label: 'Completed', value: 'Completed'},
  {label: 'Cancelled', value: 'Cancelled'},
];

export const rosterProgramTypeFilterData: any = [
  {label: 'Class', value: 'class'},
  {label: 'Tournament', value: 'tournament'},
  {label: 'League', value: 'league'},
];

export const facilityProgramInviteSortingData = [
  {label: 'Sent On (New to Old)', value: 'date/DESC'},
  {label: 'Registration Due Date(Soonest)', value: 'due_date/ASC'},
  {label: 'Price (ASC)', value: 'price/ASC'},
  {label: 'Price (DESC)', value: 'price/DESC'},
];

export const newClubProgramSortingData = [
  {label: 'Open Program (ASC)', value: 'open_programs/ASC'},
  {label: 'Open Program (DESC)', value: 'open_programs/DESC'},
  {label: 'Max Price (ASC)', value: 'price/ASC'},
  {label: 'Max Price (DESC)', value: 'price/DESC'},
  {label: 'Club Name (A to Z)', value: 'name/ASC'},
  {label: 'Club Name (Z to A)', value: 'name/DESC'},
];

export const newFacilityProgramSortingData = [
  {label: 'Created On (New to Old)', value: 'latest/DESC'},
  {label: 'Registration Due Date (Soonest)', value: 'due_date/ASC'},
  {label: 'Price (ASC)', value: 'price/ASC'},
  {label: 'Price (DESC)', value: 'price/DESC'},
  {label: 'Division (ASC)', value: 'divisions/ASC'},
  {label: 'Division (DESC)', value: 'divisions/DESC'},
];

export const facilitySubProgramSortingData = [
  {label: 'Division Name (A to Z)', value: 'division_name/ASC'},
  {label: 'Division Name (Z to A)', value: 'division_name/DESC'},
  {label: 'Open Spots (ASC)', value: 'open_spots/ASC'},
  {label: 'Open Spots (DESC)', value: 'open_spots/DESC'},
  {label: 'Date of Birth (ASC)', value: 'date_of_birth/ASC'},
  {label: 'Date of Birth (DESC)', value: 'date_of_birth/DESC'},
];

export const clubSubProgramSortingData = [
  {label: 'Created On (New to Old)', value: 'latest/DESC'},
  {label: 'Registration Due Date (Soonest)', value: 'due_date/ASC'},
  {label: 'Price (ASC)', value: 'price/ASC'},
  {label: 'Price (DESC)', value: 'price/DESC'},
  {label: 'Date of Birth (ASC)', value: 'date_of_birth/DESC'},
  {label: 'Date of Birth (DESC)', value: 'date_of_birth/ASC'},
];

export const teamsSortingData = [
  {label: 'Created On (New to Old)', value: 'latest/DESC'},
  {label: 'Registration Due Date (Soonest)', value: 'due_date/ASC'},
  {label: 'Team Name (A to Z)', value: 'team_name/ASC'},
  {label: 'Team Name (Z to A)', value: 'team_name/DESC'},
  {label: 'Price (ASC)', value: 'price/ASC'},
  {label: 'Price (DESC)', value: 'price/DESC'},
  {label: 'Date of Birth (ASC)', value: 'date_of_birth/ASC'},
  {label: 'Date of Birth (DESC)', value: 'date_of_birth/DESC'},
];

export const newClubTeamSortingData = [
  {label: 'Club Name (A to Z)', value: 'name/ASC'},
  {label: 'Club Name (Z to A)', value: 'name/DESC'},
  {label: 'Open Teams (ASC)', value: 'open_teams/ASC'},
  {label: 'Open Teams (DESC)', value: 'open_teams/DESC'},
  {label: 'Max Price (ASC)', value: 'price/ASC'},
  {label: 'Max Price (DESC)', value: 'price/DESC'},
];

export const exclusiveTeamInviteSortingData = [
  {label: 'Sent On (New to Old)', value: 'sent_on/DESC'},
  {label: 'Registration Due Date(Soonest)', value: 'due_date/ASC'},
  {label: 'Price (ASC)', value: 'price/ASC'},
  {label: 'Price (DESC)', value: 'price/DESC'},
  {label: 'Team Name (A to Z)', value: 'team_name/ASC'},
  {label: 'Team Name (Z to A)', value: 'team_name/DESC'},
];

export const TeamStr = {
  PLAYER: 'Player',
  COACH: 'Coach',
  HEAD_COACH: 'Head Coach',
  NEW_TEAM_TITLE: 'New Team',
  TEAMS_LIST: 'Teams List',
  VIEW_TEAMS: 'View Teams',
  OPEN_TEAMS: 'Open Teams:',
  TEAM_START_DATE: 'Team Start Date:',
  TEAM_END_DATE: 'Team End Date:',
  TEAM_REGISTRATION_DUE: 'Registration Due:',
  REGISTERED_ON: 'Registered On:',
  DOB_RANGE: 'DOB Range:',
  LEVEL: 'Level:',
  OPEN_SPOTS: 'Open Spots:',
  REGISTER: 'Register',
  SELECT_JERSEY: 'Select Jersey',
  JERSEY_NO: 'JERSEY NO.',
  NAME: 'NAME',
  NO_TEAMS_AVAILABLE: 'No Teams Available',
  REGISTER_ON_DESC: 'Registered on (New to Old)',
  TEAM_NAME_ASC: 'Team Name (A to Z)',
  TEAM_NAME_DESC: 'Team Name (Z to A)',
  NAME_ASC: 'Name (A to Z)',
  NAME_DESC: 'Name (Z to A)',
  MEMBER: 'Member:',
  VIEW_ROSTER: 'View Roster',
  VIEW_REQUEST: 'View Request',
  LEAVE_TEAM: 'Leave Team',
  REQUEST_TO_LEAVE: 'Request To Leave',
  MESSAGE: 'Message',
  ALL: 'All',
  MY_FAMILY: 'My Family',
  OTHERS: 'Others',
  SEARCH_ROSTER_BY_NAME: 'Search By Name',
  ROSTER_LIST: 'Roster List',
  VIEW_PROGRAMS: 'View Program(s)',
  GENERAL: 'General',
  GUARDIAN: 'Guardian',
  FIRST_NAME: 'First Name:',
  LAST_NAME: 'Last Name:',
  DATE_OF_BIRTH: 'Date of Birth:',
  GRADUATION_YEAR: 'Graduation Year:',
  EMAIL: 'Email:',
  PHONE: 'Phone:',
  GENDER: 'Gender:',
  PLAYER_ROLE: 'Player Role:',
  JERSEY_NUMBER: 'Jersey Number:',
  CLOTHING_SIZE: 'Clothing Size:',
  BIRTH_CERTIFICATE: 'Birth Certificate:',
  DETAILS: 'Details',
  NO_FILE_UPLOADED: 'No File Uploaded',
  NO_GUARDIANS_AVAILABLE: 'No Guardians Available!',
  TEAM_LEAVE: 'Team Leave',
  IN_REVIEW: 'In Review',
  NO_TEAM_PROGRAM_FOUNDS: 'No Team Programs Found!',
  SEND_EMAIL_TO_ROSTER: 'Send Email to Roster',
  SELECT_MEMBER_TO_SEND_EMAIL: 'Select Team Member(s) To Send Email',
  CONTINUE_TO_SEND_EMAIL: 'Continue To Send Email',
  SEND_EMAIL: 'Send Email',
  SENT_FROM: 'Sent From:',
  NO_TEAM_INVITE_FOUNDS: 'No team invite found!',
  SELECT_JOURSEY_NUMBER: 'Please Select Jersey Number',
  ALREADY_IN_USE: 'Already In Use',
  PREVIOUS_LABEL: 'Previous',
  NEXT_LABEL: 'Next',
  RECIPIENTS: 'Recipients',
  SUBJECT: 'Subject',
  ENTER_SUBJECT: 'Enter Subject',
  ENTER_MESSAGE: 'Enter Message',
  SUBJECT_ERROR: 'Subject is required',
  MESSAGE_ERROR: 'Message body is required',
  ENTER_MIN_MAX_DOB_DATE: 'Enter Min and Max Date of Birth',
  TEAM_ROLE: 'Team Role',
  HEAD_COACH_AGE_ERROR:
    'does not meet the minimum age requirement as a head coach',
  GENDER_ERROR:
    "cannot register for this team because you don't meet required gender or age.",
  LEAVE_TEAM_MESSAGE: 'Are you sure you want to leave the team?',
  REJECT_CONFIRMATION: 'Are your sure you want to reject the team invitation?',
};

export const ChatStr = {
  GROUP_DETAILS: 'Group Details',
  UPLOAD_GROUP_PHOTO: 'UPLOAD GROUP PHOTO',
  GROUP_PHOTO: 'Group Photo',
  PLEASE_ENTER_GNAME: 'Please enter group name',
  GROUP_NAME: 'Group Name',
  ENTER_GROUP_NAME: 'Enter group name',
  TEAM: 'Team',
  CLUB_DETAILS: 'Club Details',
  NOT_AVAILABLE: 'Not available',
  CLUB_CAT: 'Club Categories:',
  IS_REMOVED: ' is removed',
  DIRECT_MSG: 'Direct Messages',
  TEAM_CHAT: 'Team Chat',
  YOUR_CLUB_CREATED: 'Your club chat has been successfully created',
  PLEASE_SELECT_CLUB: 'Please select any club.',
  GROUP_CHAT_CREATED: 'Group chat created',
  SELECT_OR_START: 'Select or Start New Chat',
  Create_New_Chat: 'Create New Chat',
  FACILITY_DETAILS: 'Facility Details',
  CONTINUE_TO_ADD_MEMBERS: 'Continue to Add Members',
  START_NEW_GROUP_CHAT: 'Start New Group Chat',
  ADD_MEMBERS_TO_GROUP: 'Add Members to Group',
  SEARCH_PLACEHOLDER: 'Search by club, facility or group name',
  SEARCH_CLUB_PLACEHOLDER: 'Search by club name',
  SEARCH_TEAM_PLACEHOLDER: 'Search by team name',
  SEARCH_FACILITY_PLACEHOLDER: 'Search by facility name',
  SELECT_CLUB: 'Select a Club',
  SELECT_FACILITY: 'Select a Facility',
  COMPANY: 'Company',
  EMAIL: 'Email',
  START_CHAT_WITH_CLUB: 'Start Chat With Club',
  START_CHAT_WITH_FACILITY: 'Start Chat With Facility',
  TEAM_ROSTER: 'Team Roster',
  SEARCH_BY_ROLE_NAME: 'Search by role or name',
  PLEASE_ADD_MEMBERS: 'Please add members',
  SEND_MSG_TO_START_CHAT: 'Send message to start chat.',
  GROUP_MEMBERS: 'Group Members',
  MANAGE_MEMBERS: 'Manage Members',
  GROUP_DETAIL_SEARCH_PLACEHOLDER: 'Search by name or team role',
  DELETE_GROUP: 'Delete Group',
  LEAVE_GROUP_CHAT: 'Leave Group Chat',
  REMOVE_SELECTED: 'Remove Selected',
  GROUP_ADMIN: 'GROUP ADMIN',
  ADD_MEMBERS: 'Add',
  REMOVE_MEMBERS: 'Remove',
  ADD_NEW_MEMBERS: 'Add New Members',
  ADD_SELECTED_MEMBERS: 'Add Selected Members',
  DELETE_CHAT: 'Delete chat?',
  FACILITY_CHAT_CREATED: 'Your facility chat has been successfully created',
  FACILITY_CHAT_CREATE_ERROR: 'Error in create chat room for facility :--',
  PLEASE_SELECT_FACILITY: 'Please select any facility.',
  DELETE_CHAT_CONFIRMATION:
    'Are you sure you want to delete the chat?\nThis will remove all the chat history.',
  CONFIRM_LABEL: 'Confirm',
  TEAM_MEMBERS: 'Team Members',
  SEARCH_TEAM_MEMBER_PLACEHOLDER: 'Search by name or team role',
  EMPTY_TEAM_MEMBER_LIST: 'No Team Members available',
  YOU_CREATED_CHAT: 'You have created a new chat with ',
  FACILITY_SMALL_LABEL: 'facility',
  CLUB_SMALL_LABEL: 'club',
  ENTER_MESSAGE: 'Enter Message',
  FACILITY_SEARCH_PLACEHOLDER: 'Search by name, state or city',
  MEMBER_REMOVE: 'Member Remove ?',
  ARE_YOU_SURE_REMOVE: 'Are you sure you want to remove selected users.',
  MEMBER_REMOVED: 'You have successfully removed seleted members.',
  MEMBER_ADDED: 'You have successfully added seleted members.',
  MEMBER_DELETED:
    'This chat is no longer active. To start a new chat click on "New Chat" button.',
};

export const SettingsStr = {
  SETTINGS: 'Settings',
  PREFERENCES: 'PREFERENCES',
  SECURITY: 'SECURITY',
  ACCOUNT: 'ACCOUNT',
  FACE_ID: 'Face ID',
  DISABLE_FACE_ID: 'Disable Face ID',
  DELETE_ACCOUNT: 'Delete Account',
  FAMILY_ADDRESS: 'Family Address',
  CHANGE_PASSWORD: 'Change Password',
  LOGOUT: 'Logout',
  LEARN_MORE: 'Learn More >',
  HOW_FACE_ID: 'How Face ID Works?',
  HOW_FACE_ID_DES: `Enabling biometric password access does not allow Natty Hatty to access
        your biometric data. The Natty Hatty app uses the device keychain to
        store authentication tokens that only your biometrics can unlock. You
        can disable biometric authentication at any time through the Settings on
        this app.`,
  CONFIRM_TITLE: 'Disable Face/Touch ID?',
  CONFIRM_DES: 'Are you sure you want to disable face/touch ID?',
  NOT_AVAILABLE: 'Face ID/Touch ID is not available on your device.',
  ENABLE_TOUCH_ID:
    'You have to enable face/touch id first, please login with your credentials and enable face/touch id.',
};

export const FaceIdStr = {
  USE_FACE_ID: 'Use Face ID/Touch ID for Instant Sign In',
  FACE_ID: 'Face ID/Touch ID',
  CONFIRM_TITLE: 'Disable Face/Touch ID?',
  CONFIRM_DES: 'Are you sure you want to disable face/touch ID?',
  ENABLE_FACE_ID: 'Enable Face ID/Touch ID',
  DO_NOT_SHOW_AGAIN: "Don't Show Again",
  SCAN_COMPLETED: 'Scan Completed',
  SUCCESS:
    'Face ID successfully enabled. You can now instant sign in with Face ID.',
  GO_TO_DASHBOARD: 'Go To Dashboard',
  CONTINUE_TO_SETUP: 'Continue to Setup',
  TO_DISABLE: 'To disable, please go to Settings under menu option',
  KEYCHAIN_COULDN: "Keychain couldn't be accessed!",
  CONFIRM_FINGERPRINT: 'Confirm fingerprint',
};

export const CommonStr = {
  SOMETHING_WENT_WRONG: 'Something Went Wrong',
  MEMBER_SELECTION_ERROR: 'You can not select more then open slots',
};

export const AccountDeleteStr = {
  WHY_DLT_AC: 'Why Delete Account?',
  PLEASE_EXPLAIN: 'Please explain here',
  NEVERMIND: 'Nevermind, I Changed My Mind',
  CONTINUE_DLT: 'Continue Deleting Account',
  TAKE_A_BRIEF:
    "Please take a brief moment to tell us why you're deleting your account?",
  DELETE_YOUR_ACCOUNT: 'Delete Your Account',
  ARE_YOU_SURE_WANT_TO_DELETE_YOUR_ACCOUNT:
    'Are your sure you want to delete your account?',
  LOOSE_YOUR_INFO:
    'You will lose access to all of your information including registered programs, teams & more.',
  RECAP_YOUR_JOURNEY: "Here's a recap of your journey with Natty Hatty:",
  PAST_JOURNEY: 'PAST JOURNEY',
  PROGRAMS: 'Programs',
  CLUB_PROGRAMS: 'Club Programs',
  TEAMS: 'Teams',
  EVENTS: 'Events',
  CANCEL: 'Cancel',
  INVOICES: 'Invoices',
  GO_BACK: 'Go back, I Changed My Mind',
  YES_WANT_TO_LOSE_PROCESS: 'Yes, I want to lose all my progress',
  YOU_ARE_LEAVING: "We're sorry that you're leaving",
  DELETE_ACCOUNT_REQUEST_PROCESS:
    'If you confirm that you want to delete your account, we will process your request within 15 days.',
  COME_BACK_PROCESS:
    'If you change your mind, You can login back to your account to cancel the delete process within 15 days.',
  FEEDBACK: 'Feedback',
  ENTER_PASSWORD: 'Enter Password',
  ENTER_CURRENT_PASSWORD: 'Current Password',
  ENTER_YOUR_FEEDBACK: 'Enter your feedback for app',
  ACCOUNT_DELETE_TERMS_CONDITION_INSTRUCTION:
    "By checking this box you have agreed to delete your account and you agree to Natty Hatty's ",
  ACCOUNT_DELETE_PRIVACY_POLICY: 'Privacy Policy.',
  // ACCOUNT_DELETE_TERMS_CONDITION_INSTRUCTION: `By checking this box you have agreed to delete your account and you agree to Natty Hatty's Terms of Use and Privacy Policy.`,
  GO_BACK_TO_DASHBOARD: 'Nevermind, Go Back to Dashboard',
  DELETE_MY_ACCOUNT: 'Cancel My Account',
  DELETE_ACCOUNT: 'Delete Account',
  SEE_YOU_GO: "We're sorry to see you go",
  REGISTERED_DELETE_ACCOUNT_REQUEST:
    'We have registered your request to delete your account.',
  NOTE: 'Note:',
  CHANGE_MIND_NOTE:
    'If you change your mind, You can login back to your account to cancel the delete process within 15 days.',
  GOT_IT: 'Got It',
};

export const INVITE_FOR = [
  {
    label: 'Coach',
    value: 'coach',
  },
  {
    label: 'Head Coach',
    value: 'head_coach',
  },
  {
    label: 'Player',
    value: 'player',
  },
];

export const CalendarStr = {
  MY_CALENDAR: 'My Calendar',
  WEEK_VIEW: 'Week View',
  DAY_VIEW: 'Day View',
  EVENT_DETAILS: 'Event Details',
  MATCHUP: 'Matchup',
  DATE: 'Date',
  PROGRAM_TYPE: 'Program Type',
  START_TIME: 'Start Time',
  END_TIME: 'End Time',
  CATEGORY: 'Category',
  FACILITY: 'Facility',
  ADDRESS: 'Address',
  RESOURCE: 'Resource',
  SUB_RESOURCE: 'Sub Resource',
  HOME_CLUB: 'Home Club',
  HOME_COACH: 'Home Coach',
  HOME_TEAM: 'Home Team',
  AWAY_CLUB: 'Away Club',
  AWAY_COACH: 'Away Coach',
  AWAY_TEAM: 'Away Team',
  PROGRAM: 'Program',
  DIVISION: 'Division',
  STATUS: 'Status',
  UPCOMING_EVENTS: 'UPCOMING EVENTS',
  BOOKINGS: 'Bookings',
  TEAM_BOOKINGS: 'TEAM BOOKINGS',
  INDIVIDUAL_BOOKINGS: 'INDIVIDUAL BOOKINGS',
  CHOOSE_FAMILY_MEMBER: 'Choose Family Member',
  RESCHEDULE_EVENT: 'RESCHEDULE EVENT',
  CANCEL_BTN: 'Cancel',
  CONTINUE_BTN: 'Continue',
  EVENT: 'EVENT',
  REQ_TO_DELETE: 'Request To Delete',
  REQ_TO_RESCHEDULE: 'Request To Reschedule',
  View_REQ_DETAILS: 'View Request Details',
  OTHER: 'Other',
  TEAM_INFO: 'Team Info',
  CUSTOMER_INFO: 'Customer Info',
  CUSTOMER_NAME: 'Customer Name',
  CUSTOMER_EMAIL: 'Customer Email',
  CUSTOMER_PHONE_NUMBER: 'Customer Phone Number',
  CLUB_NAME: 'Club Name',
  CLUB_EMAIL: 'Club Email',
  CLUB_PHONE_NUMBER: 'Club Phone Number',
  TEAM_NAME: 'Team Name',
  UNIT_PRODUCTS: 'Unit Products',
  HOURLY_PRODUCTS: 'Hourly Products',
  TRAINERS: 'Trainers',
  REQUEST_TO_DELETE: 'Request to Delete',
  REQUEST_TO_RESCHEDULE: 'Request to Reschedule',
  VIEW_REQUEST_DETAILS: 'View Request Details',
  VALID_REASON_TO_DELETE: 'Reason for delete is required',
  VALID_REASON_TO_RESCHEDULE: 'Reason for reschedule is required',
  REQUEST_TO_DELETE_MESSAGE: 'Please give a reason requesting to delete.',
  REQUEST_TO_RESCHEDULE_MESSAGE:
    'Please give a reason for requesting to reschedule.',
  ENTER_REASON: 'Enter reason',
  SUBMIT: 'Submit',
  SUBMITTED_ASC: 'Submitted (New to Old)',
  SUBMITTED_DESC: 'Submitted (Old to New)',
  SETTLED_ASC: 'Settled (New to Old)',
  SETTLED_DESC: 'Settled (Old to New)',
  EVENT_REQUESTS: 'Event Requests',
  EVENT_NAME: 'EVENT NAME',
  REQUEST_TYPE: 'REQUEST TYPE',
  SUBMITTED_ON: 'SUBMITTED ON',
  EVENT_DATE_AND_TIME: 'EVENT DATE AND TIME',
  REQUESTED_DATE_AND_TIME: 'REQUESTED DATE AND TIME',
  SETTLED_ON: 'SETTLED ON',
  DELETE_EVENT_REQUEST_MSG: 'Are you sure you want to cancel event request?',
  DELETE_EVENT_REQUEST_TITLE: 'Cancel Event Request?',
  RESCHEDULE_EVENT_CONFIRM: 'Are you sure you want to reschedule?',
  SUCCESS_MSG: 'The request has been submitted.',
  OK: 'Ok',
  CAN_NOT_RESCHEDULE:
    'The event will be occuring within 120 hours. You can no longer reschedule',
};

export const ACC_DLT_REASONS = [
  {
    id: 0,
    value: 'Duplicate account',
    isActive: false,
  },
  {
    id: 1,
    value: 'No longer need for this service',
    isActive: false,
  },
  {
    id: 2,
    value: "I don't understand how it works",
    isActive: false,
  },
  {
    id: 3,
    value: 'I have privacy concern',
    isActive: false,
  },
  {
    id: 4,
    value: 'Other',
    isActive: false,
  },
];
export const TimeSlots = [
  '00:00',
  '00:30',
  '01:00',
  '01:30',
  '02:00',
  '02:30',
  '03:00',
  '03:30',
  '04:00',
  '04:30',
  '05:00',
  '05:30',
  '06:00',
  '06:30',
  '07:00',
  '07:30',
  '08:00',
  '08:30',
  '09:00',
  '09:30',
  '10:00',
  '10:30',
  '11:00',
  '11:30',
  '12:00',
  '12:30',
  '13:00',
  '13:30',
  '14:00',
  '14:30',
  '15:00',
  '15:30',
  '16:00',
  '16:30',
  '17:00',
  '17:30',
  '18:00',
  '18:30',
  '19:00',
  '19:30',
  '20:00',
  '20:30',
  '21:00',
  '21:30',
  '22:00',
  '22:30',
  '23:00',
  '23:30',
];
